# Generated by Django 3.1 on 2020-08-11 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservation', '0002_auto_20200811_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refid', models.IntegerField()),
                ('authority', models.CharField(max_length=40)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('paid', models.BooleanField(default=False)),
                ('status', models.IntegerField()),
                ('reserve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserve_payments', to='reservation.reservation')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداختی\u200cها',
                'ordering': ('-created',),
            },
        ),
    ]
