# Generated by Django 3.1 on 2020-08-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200809_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.IntegerField(blank=True, max_length=11, null=True, verbose_name='شماره موبایل'),
        ),
    ]
