# Generated by Django 3.1 on 2020-08-08 20:39

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('slug', models.SlugField(max_length=70)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Saloon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('about', ckeditor_uploader.fields.RichTextUploadingField()),
                ('area', models.CharField(max_length=50)),
                ('start_time', models.PositiveIntegerField()),
                ('end_time', models.PositiveIntegerField()),
                ('amount', models.PositiveIntegerField()),
                ('on_map', models.CharField(blank=True, max_length=100, null=True)),
                ('province', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('su', 'چمن'), ('sa', 'سالن')], default='su', max_length=2)),
                ('gender', models.CharField(choices=[('m', 'آقایان'), ('f', 'بانوان'), ('b', 'آقایان و بانوان')], default='b', max_length=1)),
                ('status', models.CharField(choices=[('a', 'فعال'), ('d', 'غیرفعال')], default='d', max_length=1)),
                ('features', models.ManyToManyField(related_name='features', to='saloons.Feature')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
