# Generated by Django 3.1 on 2020-08-08 21:15

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('saloons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feature',
            options={'ordering': ('-created',), 'verbose_name': 'امکان', 'verbose_name_plural': 'امکانات'},
        ),
        migrations.AlterModelOptions(
            name='saloon',
            options={'ordering': ('-created',), 'verbose_name': 'سالن', 'verbose_name_plural': 'سالن\u200cها'},
        ),
        migrations.AlterField(
            model_name='feature',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان افزودن'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=models.CharField(max_length=70, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='slug',
            field=models.SlugField(max_length=70, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='saloon',
            name='about',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='درباره سالن'),
        ),
        migrations.AlterField(
            model_name='saloon',
            name='address',
            field=models.TextField(verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='saloon',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='هزینه هر سانس'),
        ),
        migrations.AlterField(
            model_name='saloon',
            name='area',
            field=models.CharField(max_length=50, verbose_name='فضای سالن'),
        ),
        migrations.AlterField(
            model_name='saloon',
            name='city',
            field=models.CharField(max_length=100, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='saloon',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان افزودن'),
        ),
        migrations.AlterField(
            model_name='saloon',
            name='end_time',
            field=models.PositiveIntegerField(verbose_name='ساعت پایان'),
        ),
        migrations.AlterField(
            model_name='saloon',
            name='features',
            field=models.ManyToManyField(related_name='features', to='saloons.Feature', verbose_name='امکانات سالن'),
        ),
        migrations.AlterField(
            model_name='saloon',
            name='gender',
            field=models.CharField(choices=[('m', 'آقایان'), ('f', 'بانوان'), ('b', 'آقایان و بانوان')], default='b', max_length=1, verbose_name='مخصوص'),
        ),
        migrations.AlterField(
            model_name='saloon',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام سالن'),
        ),
        migrations.AlterField(
            model_name='saloon',
            name='on_map',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='موقعیت نقشه'),
        ),
        migrations.AlterField(
            model_name='saloon',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL, verbose_name='مالک'),
        ),
        migrations.AlterField(
            model_name='saloon',
            name='province',
            field=models.CharField(max_length=50, verbose_name='استان'),
        ),
        migrations.AlterField(
            model_name='saloon',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='saloon',
            name='start_time',
            field=models.PositiveIntegerField(verbose_name='ساعت شروع'),
        ),
        migrations.AlterField(
            model_name='saloon',
            name='status',
            field=models.CharField(choices=[('a', 'فعال'), ('d', 'غیرفعال')], default='d', max_length=1, verbose_name='وضعیت سالن'),
        ),
        migrations.AlterField(
            model_name='saloon',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='رشته\u200cهای سالن'),
        ),
        migrations.AlterField(
            model_name='saloon',
            name='type',
            field=models.CharField(choices=[('su', 'چمن'), ('sa', 'سالن')], default='su', max_length=2, verbose_name='نوع'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='saloons/%Y/%m/%d/')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='زمان افزودن')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('c', 'کاور'), ('s', 'اسلایدبار')], default='s', max_length=1)),
                ('status', models.BooleanField(default=True)),
                ('saloon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saloon_image', to='saloons.saloon')),
            ],
            options={
                'verbose_name': 'تصویر',
                'verbose_name_plural': 'تصاویر',
                'ordering': ('-created',),
            },
        ),
    ]
