# Generated by Django 3.1 on 2020-08-08 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('saloons', '0002_auto_20200809_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='picture',
            field=models.ImageField(upload_to='saloons/%Y/%m/%d/', verbose_name='انتخاب تصویر'),
        ),
        migrations.AlterField(
            model_name='image',
            name='saloon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saloon_image', to='saloons.saloon', verbose_name='انتخاب سالن'),
        ),
        migrations.AlterField(
            model_name='image',
            name='status',
            field=models.BooleanField(default=True, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='image',
            name='type',
            field=models.CharField(choices=[('c', 'کاور'), ('s', 'اسلایدبار')], default='s', max_length=1, verbose_name='نوع تصویر'),
        ),
        migrations.AlterField(
            model_name='saloon',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='اسلاگ'),
        ),
    ]
