# Generated by Django 3.1 on 2020-08-08 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saloons', '0003_auto_20200809_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saloon',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='features', to='saloons.Feature', verbose_name='امکانات سالن'),
        ),
    ]
