# Generated by Django 3.1 on 2020-08-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saloons', '0004_auto_20200809_0200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='type',
        ),
        migrations.AddField(
            model_name='saloon',
            name='picture',
            field=models.ImageField(default=0, upload_to='saloons/%Y/%m/%d/', verbose_name='انتخاب تصویر'),
            preserve_default=False,
        ),
    ]
